modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

issueTrackerURL="https://github.com/xg787/Enderscape-Sable-Compat/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"

#logoFile="examplemod.png"
authors="Xg787"
description='''
Adds Sable compat to Enderscape
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sable"
    type="required"
    versionRange="[${sable_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
   modId="enderscape"
   type="required"
   versionRange="[1.0.9]"
   ordering="NONE"
   side="BOTH"

